// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://usebdeoflkfzefwqutla.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzZWJkZW9mbGtmemVmd3F1dGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNDIwNTgsImV4cCI6MjA5MTgxODA1OH0.pQcAGBG-WKLMhr0LCNAwicsBrtjNa6r8i0WwIaAkbTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
