// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://uuguukpjjsupbjidoyde.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1Z3V1a3BqanN1cGJqaWRveWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyOTAyMjMsImV4cCI6MjA4NTg2NjIyM30.KY8pW6dmugEJaC1QmlQekxuTOroYPQnhfOgRKamkoFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
