// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://whxpzfafivwcmhqtfbvy.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoeHB6ZmFmaXZ3Y21ocXRmYnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNDY2MDYsImV4cCI6MjA5MTcyMjYwNn0.nh44uuMTi6iKT2k6d-RrZ1p0HjDyDqzJJeIFjJVGgE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
